[package]
name = "client-full-example"
version = "0.1.0"
edition = "2021"

[dependencies]
growthbook-rust = { path = "../.."}
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"